---
version: "3.3" 

# sudo docker networks create -d macvlan -o parent=ens18  --subnet 10.0.48.0/20 --gateway 10.0.56.1 --ip-range=10.0.50.1/24 --aux-address "host=10.0.50.222"  macvlan
networks:
  macvlan:
    external:
      name: macvlan
  default:
    driver: bridge

services:
  driver1:
    image: dachad/tcpgoon:latest
    container_name: driver1
    command: "run 10.0.59.139 19530 --connections 20000 -y -s 20"
    networks:
      macvlan:
        ipv4_address: 10.0.50.11 

  driver2:
    image: dachad/tcpgoon:latest
    container_name: driver2
    command: "run 10.0.59.139 19530 --connections 20000 -y -s 20"
    networks:
      macvlan:
        ipv4_address: 10.0.50.12

  # driver3:
  #   image: dachad/tcpgoon:latest
  #   container_name: driver3
  #   command: "run 10.0.59.139 19530 --connections 27000 -y -s 20"
  #   networks:
  #     macvlan:
  #       ipv4_address: 10.0.50.13

  # driver4:
  #   image: dachad/tcpgoon:latest
  #   container_name: driver4
  #   command: "run 10.0.59.139 19530 --connections 27000 -y -s 20"
  #   networks:
  #     macvlan:
  #       ipv4_address: 10.0.50.14

  # driver5:
  #   image: dachad/tcpgoon:latest
  #   container_name: driver5
  #   command: "run 10.0.59.139 19530 --connections 27000 -y -s 20"
  #   networks:
  #     macvlan:
  #       ipv4_address: 10.0.50.15

  # driver6:
  #   image: dachad/tcpgoon:latest
  #   container_name: driver6
  #   command: "run 10.0.59.139 19530 --connections 27000 -y -s 20"
  #   networks:
  #     macvlan:
  #       ipv4_address: 10.0.50.16

  # driver7:
  #   image: dachad/tcpgoon:latest
  #   container_name: driver7
  #   command: "run 10.0.59.139 19530 --connections 30000 -y -s 20"
  #   networks:
  #     macvlan:
  #       ipv4_address: 10.0.50.17


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/portainer/data:/data
      - ${DOCKERDIR}/shared:/shared
    environment:
      - portainer_data:/data