---
version: "3.3" 

# sudo docker networks create -d macvlan -o parent=ens18  --subnet 10.0.48.0/20 --gateway 10.0.56.1 --ip-range=10.0.50.1/24 --aux-address "host=10.0.50.222"  macvlan
networks:
  macvlan:
    external:
      name: macvlan
  default:
    driver: bridge

services:
  # driver1:
  #   image: dachad/tcpgoon:latest
  #   container_name: driver1
  #   command: "run 10.0.59.139 19530 --connections 20000 -y -s 20"
  #   networks:
  #     macvlan:
  #       ipv4_address: 10.0.50.11 


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/portainer/data:/data
      - ${DOCKERDIR}/shared:/shared
    environment:
      - portainer_data:/data
  
  go1:
    image: golang:1.8-alpine
    container_name: goDriver1
    command: "go run clientSpawn.go 2000"
    volumes:
      - $GODIR:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    networks:
      macvlan:
        ipv4_address: 10.0.50.11

  go2:
    image: golang:1.8-alpine
    container_name: goDriver2
    command: "go run clientSpawn.go 2000"
    volumes:
      - $GODIR:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    networks:
      macvlan:
        ipv4_address: 10.0.50.12
  
  go3:
    image: golang:1.8-alpine
    container_name: goDriver3
    command: "go run clientSpawn.go 2000"
    volumes:
      - $GODIR:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    networks:
      macvlan:
        ipv4_address: 10.0.50.13
  
  go4:
    image: golang:1.8-alpine
    container_name: goDriver4
    command: "go run clientSpawn.go 2000"
    volumes:
      - $GODIR:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    networks:
      macvlan:
        ipv4_address: 10.0.50.14

  go5:
    image: golang:1.8-alpine
    container_name: goDriver5
    command: "go run clientSpawn.go 2000"
    volumes:
      - $GODIR:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    networks:
      macvlan:
        ipv4_address: 10.0.50.15